"""add beach_incidents

Revision ID: 34c8b03c59cf
Revises: f573e5dcbaa3
Create Date: 2026-09-17 10:31:38.321832

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34c8b03c59cf'
down_revision: str | Sequence[str] | None = 'f573e5dcbaa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beach_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beach_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beach_id'], ['beaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beach_id', 'opened_at', 'observations')
    )
    op.create_index(op.f('ix_beach_incidents_beach_id'), 'beach_incidents', ['beach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beach_incidents_beach_id'), table_name='beach_incidents')
    op.drop_table('beach_incidents')
    # ### end Alembic commands ###
