"""add beach_measurements

Revision ID: 4ab5d9bff42f
Revises: 34c8b03c59cf
Create Date: 2026-09-17 11:32:44.375581

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ab5d9bff42f'
down_revision: str | Sequence[str] | None = '34c8b03c59cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beach_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beach_id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.Date(), nullable=False),
    sa.Column('ecoli', sa.String(length=80), nullable=True),
    sa.Column('enterococci', sa.String(length=80), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beach_id'], ['beaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beach_id', 'sampled_at')
    )
    op.create_index(op.f('ix_beach_measurements_beach_id'), 'beach_measurements', ['beach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beach_measurements_beach_id'), table_name='beach_measurements')
    op.drop_table('beach_measurements')
    # ### end Alembic commands ###
