"""init outfalls beaches statuses

Revision ID: 5c73841eb456
Revises: 
Create Date: 2026-09-16 12:34:32.422790

"""
from collections.abc import Sequence

import sqlalchemy as sa
from geoalchemy2 import Geometry

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c73841eb456'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('beaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_beaches_geom', 'beaches', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('outfalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('legal', 'illegal', 'unknown', name='outfallstatus'), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_outfalls_geom', 'outfalls', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('beach_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beach_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'warning', name='beachstate'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beach_id'], ['beaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beach_statuses_beach_id'), 'beach_statuses', ['beach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beach_statuses_beach_id'), table_name='beach_statuses')
    op.drop_table('beach_statuses')
    op.drop_geospatial_index('idx_outfalls_geom', table_name='outfalls', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('outfalls')
    op.drop_geospatial_index('idx_beaches_geom', table_name='beaches', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('beaches')
    # ### end Alembic commands ###
