"""add beach monitored flag

Revision ID: 91f82ddd8db2
Revises: 4ab5d9bff42f
Create Date: 2026-09-17 11:43:54.428448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f82ddd8db2'
down_revision: Union[str, Sequence[str], None] = '4ab5d9bff42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beaches', sa.Column('monitored', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beaches', 'monitored')
    # ### end Alembic commands ###
