"""add beach monitored flag

Revision ID: 91f82ddd8db2
Revises: 4ab5d9bff42f
Create Date: 2026-09-17 11:43:54.428448

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '91f82ddd8db2'
down_revision: str | Sequence[str] | None = '4ab5d9bff42f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beaches', sa.Column('monitored', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beaches', 'monitored')
    # ### end Alembic commands ###
