"""add news_items

Revision ID: a8a38d692bd7
Revises: b7e9f2a41c83
Create Date: 2026-09-19 09:38:54.610167

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8a38d692bd7"
down_revision: str | Sequence[str] | None = "b7e9f2a41c83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("relevant", sa.Boolean(), nullable=False),
        sa.Column("beach_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=True),
        sa.Column("cause", sa.Text(), nullable=True),
        sa.Column("extracted_beach", sa.String(length=255), nullable=True),
        sa.Column(
            "extracted_municipality", sa.String(length=120), nullable=True
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["beach_id"], ["beaches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "url", "beach_id", postgresql_nulls_not_distinct=True
        ),
    )
    op.create_index(
        op.f("ix_news_items_beach_id"),
        "news_items",
        ["beach_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("device_tokens_token_key"), "device_tokens", type_="unique"
    )
    op.drop_index(op.f("ix_device_tokens_token"), table_name="device_tokens")
    op.create_index(
        op.f("ix_device_tokens_token"), "device_tokens", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_tokens_token"), table_name="device_tokens")
    op.create_index(
        op.f("ix_device_tokens_token"),
        "device_tokens",
        ["token"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("device_tokens_token_key"),
        "device_tokens",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_news_items_beach_id"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
