"""add external_id and kind

Revision ID: f573e5dcbaa3
Revises: 5c73841eb456
Create Date: 2026-09-16 12:55:26.854358

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f573e5dcbaa3"
down_revision: str | Sequence[str] | None = "5c73841eb456"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "beaches",
        sa.Column("external_id", sa.String(length=80), nullable=True),
    )
    op.create_index(
        op.f("ix_beaches_external_id"), "beaches", ["external_id"], unique=True
    )
    op.add_column(
        "outfalls",
        sa.Column("external_id", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "outfalls", sa.Column("kind", sa.String(length=80), nullable=True)
    )
    op.create_index(
        op.f("ix_outfalls_external_id"),
        "outfalls",
        ["external_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outfalls_external_id"), table_name="outfalls")
    op.drop_column("outfalls", "kind")
    op.drop_column("outfalls", "external_id")
    op.drop_index(op.f("ix_beaches_external_id"), table_name="beaches")
    op.drop_column("beaches", "external_id")
    # ### end Alembic commands ###
